### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by AirLabCloud** [Syota-Yamaguchi/furima-29271#9]
#URL
https://furima-29271.herokuapp.com/
#Basic認証のIDとパスワード
*ID:"admin"
*パスワード:"2222"
#出品者用のメールアドレスとパスワード
*メールアドレス:"test1@sample.jp"
*パスワード:"123asd"
#購入者用のメールアドレスとパスワード
*メールアドレス:"test2@sample.jp"
*パスワード:"123asd"
#8 購入用カードの番号・期限・セキュリティコード
*番号:4242424242424242
*期限:12/2023
*セキュリティコード:123

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
[修正箇所]
・Basic認証を突破できないので、できるようにしましょう
└試したのは下記の2パターンです
```
①
ID　　admin
pass　2222

②
ID　　"admin"
pass　"2222" 
```
※上記の問題により、その他の挙動確認が一切できていないため、次回以降に確認させていただきます！

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
### [修正箇所]
**①購入ボタンを押すとエラーになり、購入が完了できないので、完了できるようにしましょう*

<img width="512" alt="スクリーンショット 2020-09-23 17 19 05" src="https://user-images.githubusercontent.com/49669977/93986260-11f4e900-fdc1-11ea-876a-a80ffb7443b3.png">



※上記のため下記5項目は次回以降に確認いたします。
`
◯購入が完了したら、トップページまたは購入完了ページに遷移する
◯売却済みの商品は、「sould out」の文字が表示されるようになっている
◯購入した商品は、再度購入できない状態になっている
◯出品者だけが商品情報を削除できる
◯ログアウトした状態でも、商品一覧を閲覧できる`

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
